### ISSUE TITLE
Add accessibility identifier to Copy OC Login Command menu item from main menu

### ISSUE THREAD

**Issue by adrianriobo** [code-ready/tray-macos#101]
Copy OC Login command from main menu has an identifier of AX on its menu [see](https://github.com/code-ready/tray-macos/blob/7ee5ef0c8fee800933f48814538c01a4525846fe/CodeReady%20Containers/Base.lproj/Main.storyboard#L103)

To access that menu it is required to click on the [menu item](https://github.com/code-ready/tray-macos/blob/7ee5ef0c8fee800933f48814538c01a4525846fe/CodeReady%20Containers/Base.lproj/Main.storyboard#L84) from the main menu, so this element also requires an AXIdentifier for better AX support

**Comment by anjannath** [comment]
@adrianriobo Added https://github.com/code-ready/tray-macos/pull/102/commits/9b5b93fdfb6416feb4728e7955f83db92efbc394 for this.
