### ISSUE TITLE
Tray crashes as soon as click on it

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/tray-macos#112]
A strange behavior in my Mac where the tray disappear as soon as I click on it to perform any kind of action. When checking the logs from the daemon it says `stdin is closed, shutdown...` which is because tray is crashed. I am not sure why it is crashed so added crash report. For me it is constantly happening even after system reboot.

```
➜  sw_vers
ProductName:	macOS
ProductVersion:	11.4
BuildVersion:	20F71
```

[crash.zip](https://github.com/code-ready/tray-macos/files/6667137/crash.zip)

**Comment by praveenkumar** [comment]
Discussed more with @anjannath and looks like it is happening when kubeconfig file exist but doesn't have any content.

```
$ cat ~/.kube/config 
apiVersion: v1
clusters: null
contexts: null
current-context: ""
kind: Config
preferences: {}
users: null
```

**Comment by guillaumerose** [comment]
It happens when the user has only crc contexts and he hits the Delete button or use `crc delete`. 

A workaround is to delete the ~/.kube/config file and restart the application.
