### ISSUE TITLE
Doesn't pop up when cluster started or failed to start

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/tray-macos#12]
Tray does't inform user if the cluster creation failed or some error occurred like pull secret not set or bundle doesn't present, also after we click on `start` then `stop` and `delete` option pops up which doesn't make sense.

- refer #11 also

**Comment by guillaumerose** [comment]
> Tray does't inform user if the cluster creation failed or some error occurred like pull secret not set or bundle doesn't present

This is working now.

> also after we click on start then stop and delete option pops up which doesn't make sense.

All buttons are activated all the time for now. Until the status is better!
