### ISSUE TITLE
Do not use the acronyms on about dialog

### ISSUE THREAD

**Issue by gorkem** [code-ready/tray-macos#16]
About dialog uses acronyms _Crc_ and _OCP_ which are not part of the branding and should not be used on  the material

**Comment by gbraad** [comment]
What would be the best way to handle this? OpenShift Container Platform might not fit properly or has to be fit on two lines (first line the product name, second line, right-aligned the version).

**Comment by gorkem** [comment]
See also https://github.com/code-ready/tray-macos/issues/4#issuecomment-581706925
