### ISSUE TITLE
Detailed status not showing any information

### ISSUE THREAD

**Issue by jsliacan** [code-ready/tray-macos#35]
The status in the tray menu seems alright, but detailed status is `Unknown` for all items listed on it. Does not change when further actions are performed from the tray or the CLI.

![Screenshot from 2020-05-29 10-47-51](https://user-images.githubusercontent.com/2056138/83249723-4bb53a80-a1a7-11ea-9fae-2aba292611e7.png)

**Comment by jsliacan** [comment]
Seems related to #31, at least superficially.

**Comment by guillaumerose** [comment]
The status is now always known (there is a loop that fetchs the status every Xs). As soon as the window opens, the status is already present.
