### ISSUE TITLE
Polish information in About section

### ISSUE THREAD

**Issue by jsliacan** [code-ready/tray-macos#36]
1. In the 'About' section of the tray, `CodeReady Containers` is not referred to consistently. E.g. `Crc Tray Version` should probably read `CodeContainers Tray Version` to be aligned with the rest of the info on the popup. 

2. Outdated information: CodeReady Containers Version is currently `1.2.1` and OCP Bundle Version is currently `4.2.2`

**Comment by anjannath** [comment]
This is probably from an old version of the tray, It was fixed in the last release of the tray..
See attached screenshot.. 
<img width="1680" alt="Screenshot 2020-05-29 at 5 48 11 PM" src="https://user-images.githubusercontent.com/8885742/83259219-47a01180-a1d5-11ea-915d-49db1fb060df.png">
