### ISSUE TITLE
Start does not work from the tray

### ISSUE THREAD

**Issue by jsliacan** [code-ready/tray-macos#41]
- Mac 10.14
- Hyperkit
- CRC version:
```bash
CodeReady Containers version: 1.13.0+8070bae
OpenShift version: 4.5.1 (embedded in binary)
```
1. `crc config set pull-secret-file <location>`
2. `crc setup --enable-experimental-features`
3. Go to tray and press _Start_

### Expected
CRC starts and status is `Running`.

### Actual
CRC fails to start with these logs: https://pastebin.com/wKzu7myx

### Note
Start works OK from the CLI and also interaction with the daemon (`crc deamon`) starts CRC as expected.

**Comment by guillaumerose** [comment]
I believe this is fixed now. At least it works for me now.
