### ISSUE TITLE
Add config window simplification

### ISSUE THREAD

**Issue by gbraad** [code-ready/tray-macos#51]
Please include if possible the single toggle: https://github.com/code-ready/crc/issues/1796 Checking this would have to disable the rest of the options?

**Comment by anjannath** [comment]
As a first step changed all the preflight configs from combo boxes to check boxes

### Screenshot
![Screenshot 2020-12-30 at 10 44 43 PM](https://user-images.githubusercontent.com/8885742/103369760-fe100000-4af0-11eb-9830-5d2a324b11f6.png)

**Comment by anjannath** [comment]
As per discussions we are not adding a `Skip All` option, rather de-clutter the UI by removing all the _Preflight Check_ options from the advanced tab
