### ISSUE TITLE
Rearrange config options in the preferences window

### ISSUE THREAD

**Issue by anjannath** [code-ready/tray-macos#52]
There are some options in the preferences window which fits better in the second tab (Advanced tab will be added), this issue is to list out what config option goes where and also which ones to keep in the UI.

### Current Preferences window
![](https://user-images.githubusercontent.com/8885742/103991957-734a9780-51b9-11eb-94cb-e74ab6c83f56.png)

**Comment by gbraad** [comment]
Consider to approach the design as a slab that is landscape, rather than portrait too

**Comment by guillaumerose** [comment]
Bundle text field can be removed.

**Comment by gbraad** [comment]
decrease the size for the memory and disksize fields a little, so the CPU can be identical?
or at least group them clearly.

the size of the cpu COULD be slightly made to look biger is you add `[no]{+]{-}` buttons around it to increase and decrease the amount of CPU.... in that case we might not need to modify the size of the other fields...

... but the pull-secret in the middle of two distinctly VM related settings is not a good one... move it down or all the way up.

**Comment by anjannath** [comment]
It was also suggested to move the proxy stuff to the "Advanced" tab? I think it makes sense to do that as i don't think a lot of users need that, WDYT?

**Comment by anjannath** [comment]
### Screenshot of the new design /cc @code-ready/crc-devel 

![Screenshot 2021-01-29 at 11 38 11 AM](https://user-images.githubusercontent.com/8885742/106238289-969bbc00-6226-11eb-9732-7eda08ad73cb.png)

**Comment by gbraad** [comment]
better, but several spelling mistakes.
Also, the spacing between the descriptuion and the property is not same for all; disksize for instance is spaced further away than memory and cpu... actually, looks like the top two are wrong.

**Comment by gbraad** [comment]
also, it is probably better to say the same as the property; "Consent about reporting telemetry"... better aks Kevin?

**Comment by gbraad** [comment]
BTW, Apply should be lower to the bottom of the window. It now feels related to Nameserver only.

**Comment by anjannath** [comment]
> also, it is probably better to say the same as the property; "Consent about reporting telemetry"... better aks Kevin?

/cc @robin-owen Hi, can you please take a look at this, please suggest if any other sentences needs to be changed/improved (like the info for the pull-secret..)

**Comment by gbraad** [comment]
Note: Already pointed about the 'Redhat' mistake.

**Comment by guillaumerose** [comment]
vsock network mode toggle require to run crc setup. It's not possible to do it from the UI, so I guess, it's better to drop this option. Hopefully, this will be the default behavior soon!

**Comment by anjannath** [comment]
This is how it looks now https://github.com/code-ready/tray-macos/pull/50#issue-531715598

**Comment by anjannath** [comment]
Done in #50
