### ISSUE TITLE
Use http over unix socket domain instead of a custom protocol

### ISSUE THREAD

**Issue by guillaumerose** [code-ready/tray-macos#53]
It would be better to use a well known protocol for the tray communication. HTTP is widely used now and most of the time a library is available.

Here we could use https://github.com/swift-server/async-http-client.

**Comment by anjannath** [comment]
Thanks, this is the interesting part https://github.com/swift-server/async-http-client#unix-domain-socket-paths

**Comment by anjannath** [comment]
Fixed in #108
