### ISSUE TITLE
Pull secret file validation too strict

### ISSUE THREAD

**Issue by jsliacan** [code-ready/tray-macos#56]
When browsing for pull secret file from the tray, files without `.json` extension are greyed out. Including `.txt` and no-extension files. See attached printscreens.

<img width="716" alt="Screenshot 2021-02-08 at 08 48 15" src="https://user-images.githubusercontent.com/2056138/107212997-10425f80-6a08-11eb-8130-99db06a882ef.png">

<img width="716" alt="Screenshot 2021-02-08 at 09 08 19" src="https://user-images.githubusercontent.com/2056138/107213018-18020400-6a08-11eb-89f9-ab167c377ec6.png">

**Comment by anjannath** [comment]
@jsliacan commit https://github.com/code-ready/tray-macos/pull/65/commits/ebbc9c5426591cbb528f7a445d61872fbd91794b  should fix this, you can try out the build from that PR to test this.
