### ISSUE TITLE
Foreground colors in About window don't work with light mode

### ISSUE THREAD

**Issue by jsliacan** [code-ready/tray-macos#57]
This is 11.2 (Big Sur). Only logo is problematic, text OK.

<img width="481" alt="Screenshot 2021-02-09 at 12 48 01" src="https://user-images.githubusercontent.com/2056138/107360511-549c3100-6ad6-11eb-8a15-d7fea406bd1c.png">
<img width="481" alt="Screenshot 2021-02-09 at 12 52 43" src="https://user-images.githubusercontent.com/2056138/107360520-57972180-6ad6-11eb-96a5-ccb92dd44c5b.png">

**Comment by anjannath** [comment]
Looks like templated images are not working as expected for big sur, The image is correctly adjusted in light mode for catalina 10.15.7, have to test out all the other images also if they are working as expected.

#### Screenshot from catalina
![Screenshot 2021-02-11 at 11 51 43 AM](https://user-images.githubusercontent.com/8885742/107607523-84c30b80-6c5f-11eb-846e-dbc6cfa78df2.png)

**Comment by anjannath** [comment]
@jsliacan Still haven't updated to big sur, but i updated Xcode and it now has the big sur sdks, which i think should fix this issue, can you please try out this build (https://54-241065687-gh.circle-artifacts.com/0/crc-tray-macos.tar.gz) and check if the color issue is fixed now.

**Comment by jsliacan** [comment]
Sorry, still seems the same with Light theme on OS level. 

<img width="479" alt="Screenshot 2021-02-24 at 12 22 54" src="https://user-images.githubusercontent.com/2056138/108993607-1c325080-769b-11eb-96bd-98163a8fab21.png">

**Comment by cfergeau** [comment]
Same issue with 10.14

**Comment by guillaumerose** [comment]
Fixed by https://github.com/code-ready/tray-macos/commit/7e484035b911c3313507edcd1f053e3167fe5ed6
