### ISSUE TITLE
Ask for the text pull secret instead of a file

### ISSUE THREAD

**Issue by guillaumerose** [code-ready/tray-macos#60]
Each time the user clicks start, the tray asks for the pull secret. 
We could ask the user to copy/paste the secret in a text box and put it in the keystore for future usage.

**Comment by anjannath** [comment]
The daemon API doesn't support this currently, we can only pass the path to pull-secret-file for the start command. also the config `pull-secret-file` is available in the preferences window which  user can configure.

**Comment by anjannath** [comment]
done in https://github.com/code-ready/tray-macos/pull/110
