### ISSUE TITLE
Details dialog window not showing the openshift version

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/tray-macos#66]
<img width="395" alt="Screenshot 2021-03-01 at 1 23 22 PM" src="https://user-images.githubusercontent.com/410007/109467525-4ddb5b00-7a91-11eb-90d4-38e498c8fe8d.png">

**Comment by anjannath** [comment]
Fixed in https://github.com/code-ready/tray-macos/pull/88/commits/b8aeea6070235c8fa182d953194de232e65a809f
