### ISSUE TITLE
Rename "Detailed status" to "Status..."

### ISSUE THREAD

**Issue by cfergeau** [code-ready/tray-macos#76]
I'm not sure the "detailed" part is adding much. The `...` indicate that this will open an additional window.
The status window title could also be just "Status"
It's possible to open multiple 'Status' windows, not sure this is intentional.

**Comment by guillaumerose** [comment]
It is now "Status and Logs". 

> It's possible to open multiple 'Status' windows, not sure this is intentional.

It is fixed now
