### ISSUE TITLE
"not now" feels out of place in error dialogs

### ISSUE THREAD

**Issue by cfergeau** [code-ready/tray-macos#78]
I just got a cluster startup failure ,the dialog says

> Failed to start OpenShift cluster
> [some details about the failure]

and the button are "Not Now" and "Check Logs". I would expect the "Not Now" to be an answer to "Failed to start OpenShift cluster", which does not make sense. It's probably related to the "Check Logs" button, but I don't think this is a very common way of using it, and since the "Check Logs" button is right of "Not Now", this does not read nicely.
I'm not sure what the UI guidelines are on macos, but it would feel easier to use to have the button to dismiss the dialog in the bottom right, and to have the 'advanced/more details'  button to the left.

**Comment by anjannath** [comment]
Fixed in #88
