### ISSUE TITLE
Run the daemon as a child process of the tray

### ISSUE THREAD

**Issue by guillaumerose** [code-ready/tray-macos#89]
Currently, the two processes are separated. As a user, if I hit a bug, I will restart the tray (and not the daemon). The state of the daemon will not be reset-ed and I will still be blocked.

If the daemon is a child of the tray, it will be also reset-ed.

**Comment by gbraad** [comment]
that is not necessarily the case... or are you only referring to the use on Linux/Un*x-like OSes?

**Comment by guillaumerose** [comment]
Fixed in master
