### ISSUE TITLE
Unified format on Notifications

### ISSUE THREAD

**Issue by adrianriobo** [code-ready/tray-macos#98]
After the execution of the actions from the tray we are getting a notification on the Notification Center. As you can see from the picture the format for the notification is not unified. 

### Stop notification
Stop sub tittle does includes the action
Stop body message includes same reworded message from subtitle 

### Start notification
Start sub title does not include any action or resulting information
Start body message define the current state of the cluster and nothing about the action

![NotificationsFormat](https://user-images.githubusercontent.com/1957899/113575766-a963b000-961e-11eb-9204-a14b3dbba47f.png)

**Comment by anjannath** [comment]
I changed the message to:
SubTitle: Successfully started cluster
Body: Openshift cluster is running
